# Generated by Django 5.2.7 on 2025-10-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='receiver',
            field=models.CharField(),
        ),
    ]
