# Generated by Django 5.2.7 on 2025-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket')], default='Futsal', max_length=20),
        ),
    ]
