# Generated by Django 5.2.7 on 2025-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.IntegerField(default=0),
        ),
    ]
